name: Helloworld

on:
  workflow_dispatch:

jobs:
  DevDeployment:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment to Dev In Progress
        run: echo "Dev deployment in progres"
  TestDeployment:
    runs-on: ubuntu-latest
    steps:
      - name: Test deployment steps
        run: echo "Test deployment in progres"
